"""create_table_CentralCoast

Revision ID: 02f737124984
Revises: 20f79f33c356
Create Date: 2024-05-16 18:21:35.632371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f737124984'
down_revision: Union[str, None] = '20f79f33c356'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hill_shire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('application_num', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=255), nullable=True),
    sa.Column('payment_ref_num', sa.String(length=255), nullable=True),
    sa.Column('costs', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('letters', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
