"""create_table_CentralCoast

Revision ID: 08c4476bbd51
Revises: 2adceaac82ad
Create Date: 2024-05-11 15:27:57.866665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c4476bbd51'
down_revision: Union[str, None] = '2adceaac82ad'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realestate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('area', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('size', sa.String(length=512), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=512), nullable=True),
    sa.Column('type', sa.String(length=126), nullable=True),
    sa.Column('price', sa.String(length=512), nullable=True),
    sa.Column('completion_date', sa.String(length=126), nullable=True),
    sa.Column('working', sa.String(length=512), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('description_content', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.String(length=126), nullable=True),
    sa.Column('bathroom', sa.String(length=126), nullable=True),
    sa.Column('parkingspaces', sa.String(length=126), nullable=True),
    sa.Column('price_else', sa.String(length=512), nullable=True),
    sa.Column('address_else', sa.String(length=512), nullable=True),
    sa.Column('bedrooms_else', sa.String(length=126), nullable=True),
    sa.Column('bathroom_else', sa.String(length=126), nullable=True),
    sa.Column('parkingspaces_else', sa.String(length=126), nullable=True),
    sa.Column('href_else', sa.Text(), nullable=False),
    sa.Column('style_else', sa.String(length=512), nullable=True),
    sa.Column('title_else', sa.String(length=512), nullable=True),
    sa.Column('area_else', sa.String(length=126), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
