"""create_table_CentralCoast

Revision ID: 0ad747cfb541
Revises: f264cd7cce3f
Create Date: 2024-05-10 15:19:30.532237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad747cfb541'
down_revision: Union[str, None] = 'f264cd7cce3f'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
