"""create_table_CentralCoast

Revision ID: 0b35fb90d958
Revises: bdab68340df6
Create Date: 2024-05-08 16:30:50.408813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b35fb90d958'
down_revision: Union[str, None] = 'bdab68340df6'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_of_gosnells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('app_detail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('lodged_time', sa.Integer(), nullable=True),
    sa.Column('determined_time', sa.Integer(), nullable=True),
    sa.Column('app_outcome', sa.String(length=255), nullable=True),
    sa.Column('officer', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description_detail', sa.Text(), nullable=True),
    sa.Column('people', sa.String(length=255), nullable=True),
    sa.Column('app_related', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
