"""create_table_CentralCoast

Revision ID: 111b16f9b1fa
Revises: b8afd59fe0cb
Create Date: 2024-05-11 10:58:40.981268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111b16f9b1fa'
down_revision: Union[str, None] = 'b8afd59fe0cb'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
