"""create_table_CentralCoast

Revision ID: 11cbdab75532
Revises: 0ad747cfb541
Create Date: 2024-05-10 15:19:53.871492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cbdab75532'
down_revision: Union[str, None] = '0ad747cfb541'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('decision_', sa.String(length=255), nullable=True),
    sa.Column('decision_date', sa.Integer(), nullable=True),
    sa.Column('received_date', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=255), nullable=True),
    sa.Column('app_type', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
