"""create_table_CentralCoast

Revision ID: 121dcf84481c
Revises: 111b16f9b1fa
Create Date: 2024-05-11 10:59:05.209268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121dcf84481c'
down_revision: Union[str, None] = '111b16f9b1fa'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noosa_council',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('application_type', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=255), nullable=True),
    sa.Column('officer', sa.String(length=255), nullable=True),
    sa.Column('property_id', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('land_description', sa.Text(), nullable=True),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
