"""create_table_CentralCoast

Revision ID: 2640d8b6b91d
Revises: fba96e984ccf
Create Date: 2024-05-09 14:18:07.781442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2640d8b6b91d'
down_revision: Union[str, None] = 'fba96e984ccf'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kingborough',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('app_address', sa.String(length=255), nullable=True),
    sa.Column('advertised_date', sa.String(length=255), nullable=True),
    sa.Column('closing_date', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    op.create_table('stonnington',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_number', sa.String(length=128), nullable=True),
    sa.Column('lodged', sa.String(length=128), nullable=True),
    sa.Column('site_address', sa.Integer(), nullable=True),
    sa.Column('reason_for_permit', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('vicsmart', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.String(length=128), nullable=True),
    sa.Column('notice_of_application', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('decision_date', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=128), nullable=True),
    sa.Column('final_decision_date', sa.Integer(), nullable=True),
    sa.Column('final_decision', sa.String(length=128), nullable=True),
    sa.Column('amendment', sa.Text(), nullable=True),
    sa.Column('site_addresses', sa.Text(), nullable=True),
    sa.Column('tribunal_decision', sa.Text(), nullable=True),
    sa.Column('ward', sa.String(length=128), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
