"""create_table_CentralCoast

Revision ID: 2adceaac82ad
Revises: fc2bea9a0624
Create Date: 2024-05-11 15:09:26.923910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adceaac82ad'
down_revision: Union[str, None] = 'fc2bea9a0624'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
