"""create_table_CentralCoast

Revision ID: 2cc287067678
Revises: 593e61d1631c
Create Date: 2024-05-08 15:45:49.972940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc287067678'
down_revision: Union[str, None] = '593e61d1631c'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strathbogie_shire_council',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
