"""create_table_CentralCoast

Revision ID: 2d460fe5908a
Revises: 79b59abf1f04
Create Date: 2024-05-06 14:18:04.131537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d460fe5908a'
down_revision: Union[str, None] = '79b59abf1f04'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penrith',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('lodged', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.String(length=255), nullable=True),
    sa.Column('officer', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
