"""create_table_CentralCoast

Revision ID: 2d7aa077cfdd
Revises: 08c4476bbd51
Create Date: 2024-05-13 10:12:02.628142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7aa077cfdd'
down_revision: Union[str, None] = '08c4476bbd51'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plansa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('application_number', sa.String(length=128), nullable=True),
    sa.Column('assessment_pathway', sa.String(length=255), nullable=True),
    sa.Column('lodged', sa.Integer(), nullable=True),
    sa.Column('council_area', sa.String(length=255), nullable=True),
    sa.Column('land', sa.String(length=128), nullable=True),
    sa.Column('plan_parcel', sa.String(length=128), nullable=True),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('building_work', sa.Text(), nullable=True),
    sa.Column('planning_consent_status', sa.String(length=128), nullable=True),
    sa.Column('planning_consent_contact', sa.String(length=128), nullable=True),
    sa.Column('planning_consent_date', sa.Integer(), nullable=True),
    sa.Column('planning_consent_date_lodged', sa.Integer(), nullable=True),
    sa.Column('planning_consent_date_submitted', sa.Integer(), nullable=True),
    sa.Column('planning_consent_date_verified', sa.Integer(), nullable=True),
    sa.Column('planning_consent_decision', sa.String(length=128), nullable=True),
    sa.Column('planning_consent_decision_authority', sa.String(length=255), nullable=True),
    sa.Column('building_consent_status', sa.String(length=128), nullable=True),
    sa.Column('building_consent_contact', sa.String(length=128), nullable=True),
    sa.Column('building_consent_date', sa.Integer(), nullable=True),
    sa.Column('building_consent_date_lodged', sa.Integer(), nullable=True),
    sa.Column('building_consent_date_submitted', sa.Integer(), nullable=True),
    sa.Column('building_consent_date_verified', sa.Integer(), nullable=True),
    sa.Column('building_consent_decision', sa.String(length=128), nullable=True),
    sa.Column('building_consent_decision_authority', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
