"""create_table_CentralCoast

Revision ID: 33813c3f1677
Revises: a0322dd684c5
Create Date: 2024-05-09 10:22:01.727877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33813c3f1677'
down_revision: Union[str, None] = 'a0322dd684c5'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyogle_village',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=100), nullable=True),
    sa.Column('detail_txt', sa.Text(), nullable=True),
    sa.Column('detail_Lodged', sa.Integer(), nullable=True),
    sa.Column('detail_Determined', sa.Integer(), nullable=True),
    sa.Column('detail_status', sa.String(length=255), nullable=True),
    sa.Column('detail_cost', sa.String(length=255), nullable=True),
    sa.Column('detail_officer', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('people', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
