"""create_table_CentralCoast

Revision ID: 3b4023ff8cad
Revises: b201ec8373c9
Create Date: 2024-05-06 17:26:41.931789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4023ff8cad'
down_revision: Union[str, None] = 'b201ec8373c9'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bayside',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_of_work', sa.Text(), nullable=True),
    sa.Column('date_lodged', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=255), nullable=True),
    sa.Column('determination_details', sa.String(length=255), nullable=True),
    sa.Column('determination_date', sa.Integer(), nullable=True),
    sa.Column('application_stages_and_status', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
