"""create_table_CentralCoast

Revision ID: 3cc0766326b3
Revises: 6d8f978b5381
Create Date: 2024-05-10 15:11:03.661223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc0766326b3'
down_revision: Union[str, None] = '6d8f978b5381'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busselton', sa.Column('cost', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###
