"""create_table_CentralCoast

Revision ID: 3e095d55c03c
Revises: a987e91eaabd
Create Date: 2024-05-28 18:36:03.506559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e095d55c03c'
down_revision: Union[str, None] = 'a987e91eaabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moretonbay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=255), nullable=True),
    sa.Column('da_number', sa.String(length=255), nullable=False),
    sa.Column('lodged_date', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('statuses', sa.String(length=255), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('parcel_lot_plan', sa.Text(), nullable=True),
    sa.Column('activity_level', sa.String(length=255), nullable=True),
    sa.Column('applicant_name', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('da_number')
    )

    # ### end Alembic commands ###
