"""create_table_CentralCoast

Revision ID: 4325087a8ec4
Revises: 121dcf84481c
Create Date: 2024-05-11 11:20:18.500323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4325087a8ec4'
down_revision: Union[str, None] = '121dcf84481c'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banyule_city_council',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('applications', sa.Text(), nullable=True),
    sa.Column('amendments', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('docs', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    # ### end Alembic commands ###
