"""create_table_CentralCoast

Revision ID: 44776902fa7d
Revises: a2e5aad061f6
Create Date: 2024-05-08 16:01:15.948375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44776902fa7d'
down_revision: Union[str, None] = 'a2e5aad061f6'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('central_coast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=125), nullable=False),
    sa.Column('application_num', sa.String(length=125), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=125), nullable=True),
    sa.Column('responsible_officer', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=125), nullable=True),
    sa.Column('decision_date', sa.Integer(), nullable=True),
    sa.Column('names', sa.String(length=512), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
