"""create_table_CentralCoast

Revision ID: 499f850ae786
Revises: c1e1a1f01262
Create Date: 2024-05-06 15:00:01.405953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499f850ae786'
down_revision: Union[str, None] = 'c1e1a1f01262'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
