"""create_table_CentralCoast

Revision ID: 56e39518f9ca
Revises: b2b06ffd723b
Create Date: 2024-05-09 14:02:54.461407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e39518f9ca'
down_revision: Union[str, None] = 'b2b06ffd723b'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
