"""create_table_CentralCoast

Revision ID: 593e61d1631c
Revises: d8e7933d69f7
Create Date: 2024-05-08 15:22:15.910894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593e61d1631c'
down_revision: Union[str, None] = 'd8e7933d69f7'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
