"""create_table_CentralCoast

Revision ID: 5e19828b384f
Revises: 8c56928ce8bf
Create Date: 2024-05-09 18:37:54.669599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e19828b384f'
down_revision: Union[str, None] = '8c56928ce8bf'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busselton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('legal', sa.Text(), nullable=True),
    sa.Column('determined_date', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=512), nullable=False),
    sa.Column('cost', sa.String(length=512), nullable=False),
    sa.Column('days', sa.String(length=128), nullable=False),
    sa.Column('complete_date', sa.Integer(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    # ### end Alembic commands ###
