"""create_table_CentralCoast

Revision ID: 69bf8922d932
Revises: 74fd8157d7d0
Create Date: 2024-05-10 15:08:00.981340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bf8922d932'
down_revision: Union[str, None] = '74fd8157d7d0'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
