"""create_table_CentralCoast

Revision ID: 77dab8a9035a
Revises: 499f850ae786
Create Date: 2024-05-06 15:36:12.263328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dab8a9035a'
down_revision: Union[str, None] = '499f850ae786'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moira',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_name', sa.String(length=256), nullable=True),
    sa.Column('lodged', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
