"""create_table_CentralCoast

Revision ID: 793f079f03df
Revises: 427c255b7e4d
Create Date: 2024-05-21 15:56:45.434387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793f079f03df'
down_revision: Union[str, None] = '427c255b7e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maitland',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_', sa.String(length=255), nullable=True),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('lodged', sa.Integer(), nullable=True),
    sa.Column('work_value', sa.String(length=255), nullable=True),
    sa.Column('officer', sa.String(length=255), nullable=True),
    sa.Column('status_', sa.String(length=255), nullable=True),
    sa.Column('property_', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('applicant', sa.Text(), nullable=True),
    sa.Column('pca', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('determination', sa.String(length=255), nullable=True),
    sa.Column('determined', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.Integer(), nullable=True),
    sa.Column('notification_from', sa.Integer(), nullable=True),
    sa.Column('notification_to', sa.Integer(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
