"""create_table_CentralCoast

Revision ID: 79b59abf1f04
Revises: a96a01db4b31
Create Date: 2024-05-06 14:02:38.578452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b59abf1f04'
down_revision: Union[str, None] = 'a96a01db4b31'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
