"""create_table_CentralCoast

Revision ID: 7c159f0c5fcd
Revises: 984296961b1e
Create Date: 2024-05-07 13:49:48.937699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c159f0c5fcd'
down_revision: Union[str, None] = '984296961b1e'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
