"""create_table_CentralCoast

Revision ID: 80cfeed2db55
Revises: f72fd64af6db
Create Date: 2024-05-08 12:00:06.011948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cfeed2db55'
down_revision: Union[str, None] = 'f72fd64af6db'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('act',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_number', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('block', sa.String(length=255), nullable=True),
    sa.Column('organiion', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('application_amended', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('da_number')
    )
    # ### end Alembic commands ###
