"""create_table_CentralCoast

Revision ID: 88c128030fed
Revises: da5f31d8b452
Create Date: 2024-05-08 14:30:00.674129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88c128030fed'
down_revision: Union[str, None] = 'da5f31d8b452'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('act', sa.Column('organisation', sa.String(length=255), nullable=True))
    op.drop_column('act', 'organiion')
    # ### end Alembic commands ###
