"""create_table_CentralCoast

Revision ID: 8c56928ce8bf
Revises: fd4800399c5e
Create Date: 2024-05-09 17:57:38.581782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c56928ce8bf'
down_revision: Union[str, None] = 'fd4800399c5e'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NSW_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Record_Type', sa.String(length=255), nullable=True),
    sa.Column('File_Type', sa.String(length=255), nullable=True),
    sa.Column('District_Code', sa.String(length=255), nullable=True),
    sa.Column('Download_Date_time', sa.String(length=255), nullable=True),
    sa.Column('Submitter_userid', sa.String(length=255), nullable=True),
    sa.Column('model_pro', sa.String(length=255), nullable=True),
    sa.Column('model_promax', sa.String(length=255), nullable=True),
    sa.Column('street_no', sa.String(length=255), nullable=True),
    sa.Column('street_name', sa.String(length=255), nullable=True),
    sa.Column('suburb_', sa.String(length=255), nullable=True),
    sa.Column('postcode_', sa.String(length=255), nullable=True),
    sa.Column('area_', sa.String(length=255), nullable=True),
    sa.Column('area_type', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.String(length=255), nullable=True),
    sa.Column('settlement_date', sa.String(length=255), nullable=True),
    sa.Column('price_', sa.String(length=255), nullable=True),
    sa.Column('zoning_', sa.String(length=255), nullable=True),
    sa.Column('nature_of_property', sa.String(length=255), nullable=True),
    sa.Column('Primiary_Purchase', sa.String(length=255), nullable=True),
    sa.Column('Strata_Lot_Number', sa.String(length=255), nullable=True),
    sa.Column('Component_code', sa.String(length=255), nullable=True),
    sa.Column('Sale_Code', sa.String(length=255), nullable=True),
    sa.Column('interest_of_Sale', sa.String(length=255), nullable=True),
    sa.Column('Dealing_Number', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
