"""create_table_CentralCoast

Revision ID: 8c8115c5e63b
Revises: f4001dfaedb7
Create Date: 2024-05-07 15:27:12.162411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8115c5e63b'
down_revision: Union[str, None] = 'f4001dfaedb7'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=256), nullable=False),
    sa.Column('app_type', sa.String(length=256), nullable=True),
    sa.Column('app_description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('lodged', sa.Integer(), nullable=True),
    sa.Column('app_location', sa.String(length=256), nullable=True),
    sa.Column('pro_adderss', sa.String(length=256), nullable=True),
    sa.Column('pro_type', sa.String(length=256), nullable=True),
    sa.Column('pro_ward', sa.String(length=256), nullable=True),
    sa.Column('land_area', sa.String(length=256), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
