"""create_table_CentralCoast

Revision ID: 8e31300ddd0d
Revises: 69bf8922d932
Create Date: 2024-05-10 15:08:32.241896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e31300ddd0d'
down_revision: Union[str, None] = '69bf8922d932'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
