"""create_table_CentralCoast

Revision ID: 92b1fed0bd7e
Revises: 2d7aa077cfdd
Create Date: 2024-05-14 11:54:14.671842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b1fed0bd7e'
down_revision: Union[str, None] = '2d7aa077cfdd'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandurah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_number', sa.String(length=128), nullable=False),
    sa.Column('ApplicationType', sa.String(length=512), nullable=True),
    sa.Column('SiteName', sa.String(length=512), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Lodged', sa.Integer(), nullable=True),
    sa.Column('Accepted', sa.Integer(), nullable=True),
    sa.Column('Determined', sa.String(length=512), nullable=True),
    sa.Column('Effective', sa.Integer(), nullable=True),
    sa.Column('ModificationCategory', sa.String(length=512), nullable=True),
    sa.Column('development', sa.String(length=512), nullable=True),
    sa.Column('NSWPlanningPortal', sa.String(length=512), nullable=True),
    sa.Column('notification', sa.String(length=512), nullable=True),
    sa.Column('dwellinghouse', sa.String(length=512), nullable=True),
    sa.Column('Lapsed', sa.Integer(), nullable=True),
    sa.Column('Completed', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('people', sa.String(length=512), nullable=True),
    sa.Column('associations', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
