"""create_table_CentralCoast

Revision ID: 984296961b1e
Revises: bc9ecf6bd0bc
Create Date: 2024-05-07 11:25:54.312138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984296961b1e'
down_revision: Union[str, None] = 'bc9ecf6bd0bc'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cockburn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('status_', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
