"""create_table_CentralCoast

Revision ID: a0322dd684c5
Revises: e614829ed7f1
Create Date: 2024-05-09 09:50:58.032989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0322dd684c5'
down_revision: Union[str, None] = 'e614829ed7f1'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('town_of_victoria_park',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('app_location', sa.String(length=255), nullable=False),
    sa.Column('app_data_post', sa.Integer(), nullable=True),
    sa.Column('app_data_closing', sa.Integer(), nullable=True),
    sa.Column('app_detail_text', sa.Text(), nullable=True),
    sa.Column('people_name', sa.String(length=255), nullable=True),
    sa.Column('people_office', sa.String(length=255), nullable=True),
    sa.Column('people_phone', sa.String(length=255), nullable=True),
    sa.Column('people_email', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id'),
    sa.UniqueConstraint('app_location')
    )
    # ### end Alembic commands ###
