"""create_table_CentralCoast

Revision ID: a2e5aad061f6
Revises: 2cc287067678
Create Date: 2024-05-08 15:50:05.066406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e5aad061f6'
down_revision: Union[str, None] = '2cc287067678'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wentworth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('applicant', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('proposal', sa.String(length=512), nullable=True),
    sa.Column('notification', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('value_exgst', sa.String(length=512), nullable=True),
    sa.Column('determination_date', sa.Integer(), nullable=True),
    sa.Column('active_days', sa.String(length=512), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
