"""create_table_CentralCoast

Revision ID: a67a2f6a523b
Revises: 92b1fed0bd7e
Create Date: 2024-05-15 17:56:10.719789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67a2f6a523b'
down_revision: Union[str, None] = '92b1fed0bd7e'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('southern_town',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_group', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('certifier_approval_date', sa.Integer(), nullable=True),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
