"""create_table_CentralCoast

Revision ID: a96a01db4b31
Revises: 74096d56c5b2
Create Date: 2024-05-06 11:29:46.945169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96a01db4b31'
down_revision: Union[str, None] = '74096d56c5b2'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_number', sa.String(length=128), nullable=True),
    sa.Column('transaction_date', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Text(), nullable=True),
    sa.Column('transaction_sub_type', sa.Text(), nullable=True),
    sa.Column('registration_type', sa.Text(), nullable=True),
    sa.Column('free_hold', sa.Text(), nullable=True),
    sa.Column('usage_', sa.Text(), nullable=True),
    sa.Column('area_', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=True),
    sa.Column('property_sub_type', sa.Text(), nullable=True),
    sa.Column('amount_', sa.Text(), nullable=True),
    sa.Column('transaction_size', sa.Text(), nullable=True),
    sa.Column('property_size', sa.Text(), nullable=True),
    sa.Column('rooms', sa.Text(), nullable=True),
    sa.Column('parking', sa.Text(), nullable=True),
    sa.Column('nearest_metro', sa.Text(), nullable=True),
    sa.Column('nearest_mall', sa.Text(), nullable=True),
    sa.Column('nearest_landmark', sa.Text(), nullable=True),
    sa.Column('no_of_buyer', sa.Text(), nullable=True),
    sa.Column('no_of_seller', sa.Text(), nullable=True),
    sa.Column('master_project', sa.Text(), nullable=True),
    sa.Column('project_', sa.Text(), nullable=True),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('contract_amount', sa.Text(), nullable=True),
    sa.Column('annual_amount', sa.Text(), nullable=True),
    sa.Column('number_rooms', sa.Text(), nullable=True),
    sa.Column('no_of_units', sa.Text(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('developer_number', sa.String(length=128), nullable=True),
    sa.Column('developer_name', sa.Text(), nullable=True),
    sa.Column('adeption_date', sa.Integer(), nullable=True),
    sa.Column('project_type', sa.Text(), nullable=True),
    sa.Column('project_value', sa.Text(), nullable=True),
    sa.Column('escrow_number', sa.String(length=128), nullable=True),
    sa.Column('project_status', sa.Text(), nullable=True),
    sa.Column('completed', sa.Text(), nullable=True),
    sa.Column('inspection_date', sa.Integer(), nullable=True),
    sa.Column('completed_date', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone_authority', sa.Text(), nullable=True),
    sa.Column('total_lands', sa.Text(), nullable=True),
    sa.Column('total_buildings', sa.Text(), nullable=True),
    sa.Column('total_villas', sa.Text(), nullable=True),
    sa.Column('total_units', sa.Text(), nullable=True),
    sa.Column('property_total_type', sa.Text(), nullable=True),
    sa.Column('procedure_year', sa.String(length=128), nullable=True),
    sa.Column('land_number', sa.String(length=128), nullable=True),
    sa.Column('land_sub_number', sa.String(length=128), nullable=True),
    sa.Column('land_type', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.String(length=128), nullable=True),
    sa.Column('zip_code', sa.Text(), nullable=True),
    sa.Column('municipality_number', sa.String(length=128), nullable=True),
    sa.Column('separated_form', sa.Text(), nullable=True),
    sa.Column('separated_reference', sa.Text(), nullable=True),
    sa.Column('project_number', sa.String(length=128), nullable=True),
    sa.Column('zone_', sa.Text(), nullable=True),
    sa.Column('unit_number', sa.String(length=128), nullable=True),
    sa.Column('balcony_area', sa.Text(), nullable=True),
    sa.Column('common_area', sa.Text(), nullable=True),
    sa.Column('actual_common_area', sa.Text(), nullable=True),
    sa.Column('floor_', sa.Text(), nullable=True),
    sa.Column('room_type', sa.Text(), nullable=True),
    sa.Column('parking_allocation_type', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Integer(), nullable=True),
    sa.Column('lease_hold', sa.Text(), nullable=True),
    sa.Column('building_number', sa.Text(), nullable=True),
    sa.Column('broker_number', sa.String(length=128), nullable=True),
    sa.Column('broker_name', sa.Text(), nullable=True),
    sa.Column('gender_', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=126), nullable=True),
    sa.Column('fax_', sa.Text(), nullable=True),
    sa.Column('real_estate_number', sa.String(length=128), nullable=True),
    sa.Column('real_estate_name', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.Integer(), nullable=True),
    sa.Column('license_source', sa.Text(), nullable=True),
    sa.Column('license_type', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=128), nullable=True),
    sa.Column('license_lssue_date', sa.Integer(), nullable=True),
    sa.Column('license_expiry_date', sa.Integer(), nullable=True),
    sa.Column('chamber_commerce', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
