"""create_table_CentralCoast

Revision ID: abc4d47c25dc
Revises: 5e19828b384f
Create Date: 2024-05-10 14:24:14.531589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc4d47c25dc'
down_revision: Union[str, None] = '5e19828b384f'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lockyer_valley',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=255), nullable=False),
    sa.Column('application_group', sa.String(length=255), nullable=True),
    sa.Column('application_type', sa.String(length=255), nullable=True),
    sa.Column('assessment_type', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=255), nullable=True),
    sa.Column('finalised_date', sa.Integer(), nullable=True),
    sa.Column('associated_name', sa.String(length=255), nullable=True),
    sa.Column('association', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('land_description', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
