"""create_table_CentralCoast

Revision ID: b2b06ffd723b
Revises: 0f0f2b34df9e
Create Date: 2024-05-09 13:50:38.728257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b06ffd723b'
down_revision: Union[str, None] = '0f0f2b34df9e'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gladstone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('site_address', sa.String(length=512), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
