"""create_table_CentralCoast

Revision ID: b2f7a35c1d40
Revises: a67a2f6a523b
Create Date: 2024-05-15 18:36:18.528229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f7a35c1d40'
down_revision: Union[str, None] = 'a67a2f6a523b'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('southern_town', sa.Column('stage', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
