"""create_table_CentralCoast

Revision ID: b8afd59fe0cb
Revises: 4fbed9952794
Create Date: 2024-05-10 15:52:37.418493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8afd59fe0cb'
down_revision: Union[str, None] = '4fbed9952794'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perth', 'decision_date',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('perth', 'received_date',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
