"""create_table_CentralCoast

Revision ID: bc9ecf6bd0bc
Revises: 3b4023ff8cad
Create Date: 2024-05-07 10:58:36.292098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9ecf6bd0bc'
down_revision: Union[str, None] = '3b4023ff8cad'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('southgippsland',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=64), nullable=False),
    sa.Column('app_date', sa.Integer(), nullable=True),
    sa.Column('app_location', sa.String(length=256), nullable=True),
    sa.Column('app_type', sa.String(length=256), nullable=True),
    sa.Column('app_decision', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('app_task_type', sa.String(length=256), nullable=True),
    sa.Column('actual_started_date', sa.Integer(), nullable=True),
    sa.Column('actual_completed_date', sa.Integer(), nullable=True),
    sa.Column('app_proposal', sa.Text(), nullable=True),
    sa.Column('responsible_officer', sa.String(length=256), nullable=True),
    sa.Column('alternate_property_address', sa.String(length=256), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
