"""create_table_CentralCoast

Revision ID: bdab68340df6
Revises: 44776902fa7d
Create Date: 2024-05-08 16:11:42.852589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdab68340df6'
down_revision: Union[str, None] = '44776902fa7d'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maribyrnong_city_council',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_num', sa.String(length=100), nullable=False),
    sa.Column('app_tittle', sa.Text(), nullable=True),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('related_information', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
