"""create_table_CentralCoast

Revision ID: c1e1a1f01262
Revises: 2d460fe5908a
Create Date: 2024-05-06 14:38:50.804393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e1a1f01262'
down_revision: Union[str, None] = '2d460fe5908a'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lithgow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_group', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('lodged_date', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('determined_date', sa.Integer(), nullable=True),
    sa.Column('name_details', sa.Text(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###
