"""create_table_CentralCoast

Revision ID: c5d4d0717bef
Revises: 8c8115c5e63b
Create Date: 2024-05-07 15:49:47.616056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d4d0717bef'
down_revision: Union[str, None] = '8c8115c5e63b'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('estate_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lodged', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.String(length=2555), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('further_info_requested_date', sa.Integer(), nullable=True),
    sa.Column('further_info_received_date', sa.Integer(), nullable=True),
    sa.Column('advertising_commencement', sa.String(length=255), nullable=True),
    sa.Column('advertising_completion', sa.String(length=255), nullable=True),
    sa.Column('no_of_objections', sa.String(length=255), nullable=True),
    sa.Column('responsible_authority_outcome', sa.String(length=255), nullable=True),
    sa.Column('final_outcome', sa.String(length=255), nullable=True),
    sa.Column('final_outcome_date', sa.Integer(), nullable=True),
    sa.Column('vcat_lodged_date', sa.Integer(), nullable=True),
    sa.Column('system_status', sa.String(length=255), nullable=True),
    sa.Column('versio_lodged_date', sa.Integer(), nullable=True),
    sa.Column('permit_ext_start_date', sa.Integer(), nullable=True),
    sa.Column('permit_ext_end_date', sa.Integer(), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('land_description', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
