"""create_table_CentralCoast

Revision ID: dc842510b44d
Revises: e435e55d48ce
Create Date: 2024-05-08 18:08:44.568979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc842510b44d'
down_revision: Union[str, None] = 'e435e55d48ce'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_of_fremantle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_num', sa.String(length=255), nullable=False),
    sa.Column('app_detail', sa.Text(), nullable=True),
    sa.Column('app_group', sa.String(length=255), nullable=True),
    sa.Column('app_category', sa.String(length=255), nullable=True),
    sa.Column('app_sub_category', sa.String(length=255), nullable=True),
    sa.Column('app_status', sa.String(length=255), nullable=True),
    sa.Column('lodgement_date', sa.Integer(), nullable=True),
    sa.Column('stage_decision', sa.String(length=255), nullable=True),
    sa.Column('wapc_ref', sa.String(length=255), nullable=True),
    sa.Column('council_decision', sa.String(length=255), nullable=True),
    sa.Column('wapc_decision', sa.String(length=255), nullable=True),
    sa.Column('no_of_lots', sa.String(length=255), nullable=True),
    sa.Column('date_received', sa.Integer(), nullable=True),
    sa.Column('council_decision_date', sa.Integer(), nullable=True),
    sa.Column('wapc_decision_date', sa.Integer(), nullable=True),
    sa.Column('advertisement_commence', sa.Integer(), nullable=True),
    sa.Column('advertisement_closing', sa.Integer(), nullable=True),
    sa.Column('decision_date', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.Integer(), nullable=True),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('detail_address_description', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_num')
    )
    # ### end Alembic commands ###
