"""create_table_CentralCoast

Revision ID: e614829ed7f1
Revises: dc842510b44d
Create Date: 2024-05-09 09:50:30.809585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e614829ed7f1'
down_revision: Union[str, None] = 'dc842510b44d'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
