"""create_table_CentralCoast

Revision ID: f264cd7cce3f
Revises: 3cc0766326b3
Create Date: 2024-05-10 15:14:16.380568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f264cd7cce3f'
down_revision: Union[str, None] = '3cc0766326b3'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('busselton', 'decision',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('busselton', 'cost',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('busselton', 'days',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('busselton', '_tid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('stonnington', 'app_number',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
