"""create_table_CentralCoast

Revision ID: f4001dfaedb7
Revises: cd0688258ef2
Create Date: 2024-05-07 14:49:21.011335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4001dfaedb7'
down_revision: Union[str, None] = 'cd0688258ef2'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercialrealestate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_', sa.String(length=255), nullable=True),
    sa.Column('floor_area', sa.String(length=255), nullable=True),
    sa.Column('land_area', sa.String(length=255), nullable=True),
    sa.Column('parking', sa.String(length=255), nullable=True),
    sa.Column('annual_return', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('agent_info', sa.Text(), nullable=True),
    sa.Column('closing_date', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_number')
    )
    # ### end Alembic commands ###
