"""create_table_CentralCoast

Revision ID: f72fd64af6db
Revises: 5d0a51e72155
Create Date: 2024-05-08 11:53:18.391925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72fd64af6db'
down_revision: Union[str, None] = '5d0a51e72155'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_model', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('app_title', sa.String(length=255), nullable=True),
    sa.Column('app_status', sa.String(length=255), nullable=True),
    sa.Column('purpose_to', sa.String(length=255), nullable=True),
    sa.Column('property_features', sa.Text(), nullable=True),
    sa.Column('count_beds', sa.String(length=255), nullable=True),
    sa.Column('count_baths', sa.String(length=255), nullable=True),
    sa.Column('parking_info', sa.String(length=255), nullable=True),
    sa.Column('land_area', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain_says', sa.String(length=255), nullable=True),
    sa.Column('people_name', sa.String(length=255), nullable=True),
    sa.Column('people_address', sa.String(length=255), nullable=True),
    sa.Column('total_title', sa.String(length=255), nullable=True),
    sa.Column('total_location', sa.String(length=255), nullable=True),
    sa.Column('total_information', sa.String(length=255), nullable=True),
    sa.Column('project_highlights', sa.Text(), nullable=True),
    sa.Column('total_description', sa.Text(), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_table('realcommercial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_model', sa.String(length=255), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('purpose_to', sa.String(length=255), nullable=True),
    sa.Column('price_information', sa.String(length=255), nullable=True),
    sa.Column('land_area', sa.Text(), nullable=True),
    sa.Column('floor_area', sa.String(length=255), nullable=True),
    sa.Column('property_extent', sa.Text(), nullable=True),
    sa.Column('tenure_type', sa.String(length=255), nullable=True),
    sa.Column('car_spaces', sa.String(length=255), nullable=True),
    sa.Column('parking_info', sa.String(length=255), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('sold_on', sa.String(length=255), nullable=True),
    sa.Column('zoning_', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('people_name', sa.String(length=255), nullable=True),
    sa.Column('people_address', sa.String(length=255), nullable=True),
    sa.Column('_tid', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    # ### end Alembic commands ###
