"""create_table_CentralCoast

Revision ID: fba96e984ccf
Revises: 56e39518f9ca
Create Date: 2024-05-09 14:04:04.592857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba96e984ccf'
down_revision: Union[str, None] = '56e39518f9ca'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gladstone', sa.Column('_tid', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
