"""create_table_CentralCoast

Revision ID: fd4800399c5e
Revises: 5a921ad77ca1
Create Date: 2024-05-09 15:54:29.609509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4800399c5e'
down_revision: Union[str, None] = '5a921ad77ca1'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gladstone', ['application_id'])
    # ### end Alembic commands ###
